version: 2
jobs:
  build:
    machine: true
    branches:
      only:
        - master
    steps:
      - run:
          name: Running test
          command: karma start karma.conf.js
      - run:
          name: Generating Static content
          command: npm run generated
      - run:
          name: Deploying
          command: ./deploy-ghpages.sh .
