version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    branches:
      only:
        - master
    steps:
      - run:  |
        karma start karma.conf.js
        npm run generated
        ./deploy-ghpages.sh .
