version: 2
jobs:
  build:
    machine: true,
    steps:
      - checkout
      - run:
          name: node version and npm
          command: 'npm -v && node -v'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: npminstall
          command: 'npm install'
      - run:
          name: Running test
          command: node_modules/karma/bin/karma start karma.conf.js
      - run:
          name: Generating Static content
          command: npm run generated
      - run:
          name: Deploying
          command: ../deploy-ghpages.sh .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build


#   test:
#     machine: true,
#     steps:
#       - checkout
#       - run:
#           name: Running test
#           command: node_modules/karma/bin/karma start karma.conf.js
#
#   generate:
#     machine: true,
#     steps:
#       - checkout
#       - run:
#           name: Generating Static content
#           command: npm run generated
#
#   deploy:
#     machine: true,
#     steps:
#       - checkout
#       - run:
#           name: Deploying
#           command: ../deploy-ghpages.sh .
#
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
#       - generate:
#           requires:
#             - test
#       - deploy:
#           requires:
#             - generate
