version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout
      - run:
          name: node version and npm
          command: 'npm -v && node -v'
      - run:
          name: install karma cli
          command: 'npm install -g karma-cli'
      - run:
          name: npminstall
          command: 'npm install'

  test:
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout
      - run:
          name: Running test
          command: node_modules/karma/bin/karma start karma.conf.js

  generate:
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout
      - run:
          name: Generating Static content
          command: npm run generated

  deploy:
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout
      - run:
          name: Deploying
          command: ../deploy-ghpages.sh .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - generate:
          requires:
            - test
      - deploy:
          requires:
            - generate
