version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout
      - run:
          name: node version and npm
          command: 'npm -v && node -v'
      - run:
          name: install karma cli
          command: 'sudo npm install -g karma-cli'
      - run:
          name: npminstall
          command: 'npm install'
      - run:
          name: Running test
          command: karma start karma.conf.js
      - run:
          name: Generating Static content
          command: npm run generate
      - run:
          name: Deploying
          command: ../deploy-ghpages.sh dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
